from config.settings.base_settings import app
from applications.user_management.routes import user_management
from applications.authentication.routes import authentication
from applications.roles_management.routes import roles_management
from applications.groups_management.routes import group_management
from applications.apis_management.routes import apis_management
from applications.permissions_management.routes import permissions_management

